[tool.poetry]
name = "pjisp_diff"
version = "0.1.0"
description = ""
authors = ["Jelena Dokic <jrubics@hacke.rs>"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^7.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
